### ISSUE TITLE
Userland Jenkins Job - no space left for device after cloning bcc

### ISSUE THREAD

**Issue by sdimitro** [delphix/linux-pkg#100]
Run:
http://ops.jenkins.delphix.com/job/devops-gate/job/master/job/linux-pkg-build/job/6.0/job/stage/job/userland/job/post-push/72/execution/node/10/log/

```
Cloning the remote Git repository
15:32:19  ERROR: Error cloning remote repo 'bcc'
15:32:19  hudson.plugins.git.GitException: Command "git fetch --tags --progress -- https://github.com/delphix/bcc.git +refs/heads/*:refs/remotes/bcc/*" returned status code 128:
15:32:19  stdout: 
15:32:19  stderr: remote: Enumerating objects: 1718, done.        
15:32:19  remote: Counting objects:   0% (1/1718)        
remote: Counting objects:   1% (18/1718)        
...       
remote: Counting objects: 100% (1718/1718), done.        
15:32:19  remote: Compressing objects:   0% (1/820)       
...   
remote: Compressing objects: 100% (820/820), done.        
15:32:19  Receiving objects:   0% (1/19204)   
...
Receiving objects:  10% (1921/19204)   
fatal: write error: No space left on device
15:32:19  fatal: index-pack failed
15:32:19  
15:32:19  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandIn(CliGitAPIImpl.java:2430)
15:32:19  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.launchCommandWithCredentials(CliGitAPIImpl.java:2044)
15:32:19  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl.access$500(CliGitAPIImpl.java:81)
15:32:19  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$1.execute(CliGitAPIImpl.java:569)
15:32:19  	at org.jenkinsci.plugins.gitclient.CliGitAPIImpl$2.execute(CliGitAPIImpl.java:798)
```

**Comment by sdimitro** [comment]
This internal issue may or may not be related: https://jira.delphix.com/browse/INC-551

**Comment by pzakha** [comment]
It failed when checking out the code for polling on the Jenkins agent, so it definitely looks like INC-551. I'll close this.
